# setup 
FROM python:3.12.10-slim
WORKDIR /usr/local/app

# install ffmpeg 
RUN apt-get -y update
RUN apt-get install -y ffmpeg

# RUN apt-get install ffmpeg -y

# install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000
EXPOSE 8001

# setup app user 
RUN useradd app 
USER app

# run contianer 
COPY main.py ./
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

# CMD [ "python", "main.py" ]