# TODO: add pg image logic

version: '3.8'

services:
  # ───────────── Gateway ─────────────
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - shared_data:/data
    environment:
      PREPROCESS_SERVICE_URL: http://preprocess:8001/preprocess/
      WHISPER_SERVICE_URL:    http://whisper:8003/whisper/
      DIARIZATION_SERVICE_URL: http://diarization:8004/diarization/
      SUMMARIZATION_SERVICE_URL: http://summarization:8005/summarization/
      DB_USER: admin 
      DB_PASSWORD: secret 
      DB_HOST: 100.91.232.127
      DB_PORT: 5432 
      DB_NAME: "meetingdb"
      TZ: Asia/Bangkok
    depends_on:
      - preprocess
      - vad
      - whisper
      - diarization
      - summarization
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ─────────── Preprocessing ───────────
  # TODO: change name (preprocess->Audio Preprocessor)
  preprocess:
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - shared_data:/data
    environment:
      TZ: Asia/Bangkok
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ───────────── VAD ─────────────
  vad:
    build:
      context: ./vad
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - shared_data:/data
    environment:
      HF_TOKEN: ${HF_TOKEN}
      TZ: Asia/Bangkok
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ───────────── Whisper ──────────────
  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    volumes:
      - shared_data:/data
      - whisper_cache:/home/app/.cache
    environment:
      VAD_URL: http://vad:8002/vad/
      MODEL_ID: openai/whisper-large-v3-turbo
      LANGUAGE: th
      HF_HOME: /home/app/.cache
      NVIDIA_VISIBLE_DEVICES: all
      TZ: Asia/Bangkok
    depends_on:
      - vad
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ─────────── Diarization ────────────
  diarization:
    build:
      context: ./diarization
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    volumes:
      - shared_data:/data
    environment:
      HF_TOKEN: ${HF_TOKEN}
      TZ: Asia/Bangkok
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ───────── Summarization ────────────
  summarization:
    build:
      context: ./summarization
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    volumes:
      - shared_data:/data
    environment:
      MODEL_ID: llama3
      OLLAMA_HOST: http://ollama:11434
      TZ: Asia/Bangkok
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ───────────── File Server ──────────────
  file-server:
    build:
      context: ./file-server
      dockerfile: Dockerfile 
    ports: 
      - "8010:8010"
    volumes: 
      - shared_data:/data
    restart: unless-stopped
    networks:
      - meeting_summarization_network

  # ───────────── Ollama ──────────────
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      OLLAMA_SKIP_GPU_TESTS: "false"
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - meeting_summarization_network
# ───────────── Network & Volumes ─────────────
networks:
  meeting_summarization_network:
    driver: bridge

volumes:
  shared_data:
  whisper_cache:
  ollama_data:
